extends Node


const Fleece_Tactical_Green = preload("res://Items/Torso/Fleece_Tactical_Green/Fleece_Tactical_Green.tscn")
const Fleece_Tactical_Brown = preload("res://Items/Torso/Fleece_Tactical_Brown/Fleece_Tactical_Brown.tscn")
const Hoodie_Gray = preload("res://Items/Torso/Hoodie_Gray/Hoodie_Gray.tscn")
const Jacket_Military_M62 = preload("res://Items/Torso/Jacket_Military_M62/Jacket_Military_M62.tscn")
const Jacket_Santa = preload("res://Items/Torso/Jacket_Santa/Jacket_Santa.tscn")
const Jacket_Winter_Blue = preload("res://Items/Torso/Jacket_Winter_Blue/Jacket_Winter_Blue.tscn")
const Jacket_Winter_Red = preload("res://Items/Torso/Jacket_Winter_Red/Jacket_Winter_Red.tscn")
const Windbreaker_Black = preload("res://Items/Torso/Windbreaker_Black/Windbreaker_Black.tscn")
const Windbreaker_Green = preload("res://Items/Torso/Windbreaker_Green/Windbreaker_Green.tscn")
const Hoodie_Border_Zone = preload("res://Items/Torso/Hoodie_Border_Zone/Hoodie_Border_Zone.tscn")
const Jeans_Black = preload("res://Items/Legs/Jeans_Black.tscn")
const Pants_Hiking = preload("res://Items/Legs/Pants_Hiking.tscn")
const Gloves_Leather = preload("res://Items/Hands/Gloves_Leather.tscn")
const Gloves_Work = preload("res://Items/Hands/Gloves_Work.tscn")
const Sauna_Hat = preload("res://Items/Head/Sauna_Hat/Sauna_Hat.tscn")
const Boots_Combat = preload("res://Items/Feet/Boots_Combat.tscn")
const SSh_39 = preload("res://Items/Head/SSh-39/SSh-39.tscn")
const Helmet_Police = preload("res://Items/Head/Helmet_Police/Helmet_Police.tscn")


const Plate_Carrier = preload("res://Items/Rig/Plate_Carrier.tscn")
const LVPC_Green = preload("res://Items/Rig/LVPC/LVPC_Green.tscn")
const LVPC_M05 = preload("res://Items/Rig/LVPC/LVPC_M05.tscn")
const LVPC_Winter = preload("res://Items/Rig/LVPC/LVPC_Winter.tscn")


const Backpack_Patrol = preload("res://Items/Backpacks/Backpack_Patrol/Backpack_Patrol.tscn")
const Duffel_Retro = preload("res://Items/Backpacks/Duffel_Retro/Duffel_Retro.tscn")
const Backpack_Nomad = preload("res://Items/Backpacks/Backpack_Nomad/Backpack_Nomad.tscn")
const Backpack_Jaeger_M05 = preload("res://Items/Backpacks/Backpack_Jaeger/Backpack_Jaeger_M05.tscn")
const Backpack_Jaeger_Green = preload("res://Items/Backpacks/Backpack_Jaeger/Backpack_Jaeger_Green.tscn")
const Backpack_Jaeger_Brown = preload("res://Items/Backpacks/Backpack_Jaeger/Backpack_Jaeger_Brown.tscn")
const Backpack_Jaeger_Black = preload("res://Items/Backpacks/Backpack_Jaeger/Backpack_Jaeger_Black.tscn")


const Kukkaro_M05 = preload("res://Items/Belts/Kukkaro/Kukkaro_M05.tscn")
const Kukkaro_Green = preload("res://Items/Belts/Kukkaro/Kukkaro_Green.tscn")
const Kukkaro_Brown = preload("res://Items/Belts/Kukkaro/Kukkaro_Brown.tscn")
const Kukkaro_Black = preload("res://Items/Belts/Kukkaro/Kukkaro_Black.tscn")


const Medkit = preload("res://Items/Medical/Medkit/Medkit.tscn")
const Bandage = preload("res://Items/Medical/Bandage/Bandage.tscn")
const Splint = preload("res://Items/Medical/Splint/Splint.tscn")
const Tourniquet = preload("res://Items/Medical/Tourniquet/Tourniquet.tscn")
const Antibiotics = preload("res://Items/Medical/Antibiotics/Antibiotics.tscn")
const Cold_Medicine = preload("res://Items/Medical/Cold_Medicine/Cold_Medicine.tscn")
const Painkillers = preload("res://Items/Medical/Painkillers/Painkillers.tscn")
const IFAK = preload("res://Items/Medical/IFAK/IFAK.tscn")
const Lotion = preload("res://Items/Medical/Lotion/Lotion.tscn")
const Melatonin = preload("res://Items/Medical/Melatonin/Melatonin.tscn")


const Notes_Doctor = preload("res://Items/Lore/Notes_Doctor/Notes_Doctor.tscn")


const Ammo_9_19 = preload("res://Items/Ammo/Ammo_9_19/Ammo_9_19.tscn")
const Ammo_45 = preload("res://Items/Ammo/Ammo_45/Ammo_45.tscn")
const Ammo_762_39 = preload("res://Items/Ammo/Ammo_762_39/Ammo_762_39.tscn")
const Ammo_12_70 = preload("res://Items/Ammo/Ammo_12_70/Ammo_12_70.tscn")
const Ammo_762_54R = preload("res://Items/Ammo/Ammo_762_54R/Ammo_762_54R.tscn")
const Ammo_223 = preload("res://Items/Ammo/Ammo_223/Ammo_223.tscn")
const Ammo_308 = preload("res://Items/Ammo/Ammo_308/Ammo_308.tscn")
const Ammo_545_39 = preload("res://Items/Ammo/Ammo_545_39/Ammo_545_39.tscn")
const Ammo_9_39 = preload("res://Items/Ammo/Ammo_9_39/Ammo_9_39.tscn")
const Ammo_46_30 = preload("res://Items/Ammo/Ammo_46_30/Ammo_46_30.tscn")
const Ammo_9_18 = preload("res://Items/Ammo/Ammo_9_18/Ammo_9_18.tscn")


const Armor_Plate_II = preload("res://Items/Armor/Armor_Plate_II.tscn")
const Armor_Plate_IIIA = preload("res://Items/Armor/Armor_Plate_IIIA.tscn")
const Armor_Plate_III = preload("res://Items/Armor/Armor_Plate_III.tscn")
const Armor_Plate_III_Plus = preload("res://Items/Armor/Armor_Plate_III+.tscn")
const Armor_Plate_IV = preload("res://Items/Armor/Armor_Plate_IV.tscn")


const AKS_74U = preload("res://Items/Weapons/AKS-74U/AKS-74U_Pickup.tscn")
const KAR_21_223 = preload("res://Items/Weapons/KAR-21/KAR-21_223_Pickup.tscn")
const KAR_21_308 = preload("res://Items/Weapons/KAR-21/KAR-21_308_Pickup.tscn")
const Makarov = preload("res://Items/Weapons/Makarov/Makarov_Pickup.tscn")
const Mosin = preload("res://Items/Weapons/Mosin/Mosin_Pickup.tscn")
const KP_31 = preload("res://Items/Weapons/KP-31/KP-31_Pickup.tscn")
const RK_95 = preload("res://Items/Weapons/RK-95/RK-95_Pickup.tscn")
const MP5 = preload("res://Items/Weapons/MP5/MP5_Pickup.tscn")
const VSS = preload("res://Items/Weapons/VSS/VSS_Pickup.tscn")
const MK18 = preload("res://Items/Weapons/MK18/MK18_Pickup.tscn")
const Glock_17 = preload("res://Items/Weapons/Glock_17/Glock_17_Pickup.tscn")
const MP7 = preload("res://Items/Weapons/MP7/MP7_Pickup.tscn")
const SVD = preload("res://Items/Weapons/SVD/SVD_Pickup.tscn")
const Remington_870 = preload("res://Items/Weapons/Remington_870/Remington_870_Pickup.tscn")
const AK_12 = preload("res://Items/Weapons/AK-12/AK-12_Pickup.tscn")
const Colt_1911 = preload("res://Items/Weapons/Colt_1911/Colt_1911_Pickup.tscn")
const MP5SD = preload("res://Items/Weapons/MP5SD/MP5SD_Pickup.tscn")
const MP5K = preload("res://Items/Weapons/MP5K/MP5K_Pickup.tscn")
const AKM = preload("res://Items/Weapons/AKM/AKM_Pickup.tscn")


const Makarov_Rig = preload("res://Items/Weapons/Makarov/Makarov_Rig.tscn")
const AKS_74U_Rig = preload("res://Items/Weapons/AKS-74U/AKS-74U_Rig.tscn")
const KAR_21_223_Rig = preload("res://Items/Weapons/KAR-21/KAR-21_223_Rig.tscn")
const KAR_21_308_Rig = preload("res://Items/Weapons/KAR-21/KAR-21_308_Rig.tscn")
const Mosin_Rig = preload("res://Items/Weapons/Mosin/Mosin_Rig.tscn")
const KP_31_Rig = preload("res://Items/Weapons/KP-31/KP-31_Rig.tscn")
const RK_95_Rig = preload("res://Items/Weapons/RK-95/RK-95_Rig.tscn")
const MP5_Rig = preload("res://Items/Weapons/MP5/MP5_Rig.tscn")
const VSS_Rig = preload("res://Items/Weapons/VSS/VSS_Rig.tscn")
const MK18_Rig = preload("res://Items/Weapons/MK18/MK18_Rig.tscn")
const Glock_17_Rig = preload("res://Items/Weapons/Glock_17/Glock_17_Rig.tscn")
const MP7_Rig = preload("res://Items/Weapons/MP7/MP7_Rig.tscn")
const SVD_Rig = preload("res://Items/Weapons/SVD/SVD_Rig.tscn")
const Remington_870_Rig = preload("res://Items/Weapons/Remington_870/Remington_870_Rig.tscn")
const AK_12_Rig = preload("res://Items/Weapons/AK-12/AK-12_Rig.tscn")
const Colt_1911_Rig = preload("res://Items/Weapons/Colt_1911/Colt_1911_Rig.tscn")
const MP5SD_Rig = preload("res://Items/Weapons/MP5SD/MP5SD_Rig.tscn")
const MP5K_Rig = preload("res://Items/Weapons/MP5K/MP5K_Rig.tscn")
const AKM_Rig = preload("res://Items/Weapons/AKM/AKM_Rig.tscn")


const Monster = preload("res://Items/Attachments/Monster/Monster_Pickup.tscn")
const Hybrid = preload("res://Items/Attachments/Hybrid/Hybrid_Pickup.tscn")
const SOCOM = preload("res://Items/Attachments/SOCOM/SOCOM_Pickup.tscn")
const Thor = preload("res://Items/Attachments/Thor/Thor_Pickup.tscn")
const EXPS = preload("res://Items/Attachments/EXPS/EXPS_Pickup.tscn")
const Micro = preload("res://Items/Attachments/Micro/Micro_Pickup.tscn")
const ACOG = preload("res://Items/Attachments/ACOG/ACOG_Pickup.tscn")
const PU = preload("res://Items/Attachments/PU/PU_Pickup.tscn")
const PBS = preload("res://Items/Attachments/PBS/PBS_Pickup.tscn")
const PTN = preload("res://Items/Attachments/PTN/PTN_Pickup.tscn")
const PRO = preload("res://Items/Attachments/PRO/PRO_Pickup.tscn")
const HMR = preload("res://Items/Attachments/HMR/HMR_Pickup.tscn")
const POSP = preload("res://Items/Attachments/POSP/POSP_Pickup.tscn")
const Salvo = preload("res://Items/Attachments/Salvo/Salvo_Pickup.tscn")
const Navy = preload("res://Items/Attachments/Navy/Navy_Pickup.tscn")
const Vudu = preload("res://Items/Attachments/Vudu/Vudu_Pickup.tscn")
const Leopard = preload("res://Items/Attachments/Leopard/Leopard_Pickup.tscn")
const Kobra = preload("res://Items/Attachments/Kobra/Kobra_Pickup.tscn")
const KAR_21_Barrel = preload("res://Items/Weapons/KAR-21/KAR-21_Barrel_Pickup.tscn")
const MRO = preload("res://Items/Attachments/MRO/MRO_Pickup.tscn")
const RMR = preload("res://Items/Attachments/RMR/RMR_Pickup.tscn")
const SRO = preload("res://Items/Attachments/SRO/SRO_Pickup.tscn")
const Rider = preload("res://Items/Attachments/Rider/Rider_Pickup.tscn")


const Jaeger_140 = preload("res://Items/Knives/Jaeger_140/Jaeger_140_Pickup.tscn")
const Skrama_200 = preload("res://Items/Knives/Skrama_200/Skrama_200_Pickup.tscn")
const Skrama_240 = preload("res://Items/Knives/Skrama_240/Skrama_240_Pickup.tscn")


const Jaeger_140_Rig = preload("res://Items/Knives/Jaeger_140/Jaeger_140_Rig.tscn")
const Skrama_200_Rig = preload("res://Items/Knives/Skrama_200/Skrama_200_Rig.tscn")
const Skrama_240_Rig = preload("res://Items/Knives/Skrama_240/Skrama_240_Rig.tscn")


const Canned_Pea_Soup = preload("res://Items/Consumables/Canned_Pea_Soup/Canned_Pea_Soup.tscn")
const Canned_Meat = preload("res://Items/Consumables/Canned_Meat/Canned_Meat.tscn")
const Canned_Meatballs = preload("res://Items/Consumables/Canned_Meatballs/Canned_Meatballs.tscn")
const Canned_Pear = preload("res://Items/Consumables/Canned_Pear/Canned_Pear.tscn")
const Canned_Peaches = preload("res://Items/Consumables/Canned_Peaches/Canned_Peaches.tscn")
const Canned_Pineapple = preload("res://Items/Consumables/Canned_Pineapple/Canned_Pineapple.tscn")
const Canned_Tomatoes = preload("res://Items/Consumables/Canned_Tomatoes/Canned_Tomatoes.tscn")
const Canned_Peas = preload("res://Items/Consumables/Canned_Peas/Canned_Peas.tscn")
const Canned_Tuna = preload("res://Items/Consumables/Canned_Tuna/Canned_Tuna.tscn")
const Field_Ration = preload("res://Items/Consumables/Field_Ration/Field_Ration.tscn")
const Soda_Lemonade = preload("res://Items/Consumables/Soda_Lemonade/Soda_Lemonade.tscn")
const Pastilles_Salty_Licorice = preload("res://Items/Consumables/Pastilles_Salty_Licorice/Pastilles_Salty_Licorice.tscn")
const Pastilles_Bear = preload("res://Items/Consumables/Pastilles_Bear/Pastilles_Bear.tscn")
const Peanuts_Salted = preload("res://Items/Consumables/Peanuts_Salted/Peanuts_Salted.tscn")
const Peanuts_Honey = preload("res://Items/Consumables/Peanuts_Honey/Peanuts_Honey.tscn")
const Energy_Powder = preload("res://Items/Consumables/Energy_Powder/Energy_Powder.tscn")
const Snus_Licorice = preload("res://Items/Consumables/Snus/Snus_Licorice.tscn")
const Snus_Mint = preload("res://Items/Consumables/Snus/Snus_Mint.tscn")
const Snus_Original = preload("res://Items/Consumables/Snus/Snus_Original.tscn")
const Snus_Strong = preload("res://Items/Consumables/Snus/Snus_Strong.tscn")
const Crackers = preload("res://Items/Consumables/Crackers/Crackers.tscn")
const Juice_Box_Orange = preload("res://Items/Consumables/Juice_Box_Orange/Juice_Box_Orange.tscn")
const Juice_Box_Pear = preload("res://Items/Consumables/Juice_Box_Pear/Juice_Box_Pear.tscn")
const Juice_Box_Raspberry = preload("res://Items/Consumables/Juice_Box_Raspberry/Juice_Box_Raspberry.tscn")
const Mustard = preload("res://Items/Consumables/Mustard/Mustard.tscn")
const Cooked_Pea_Soup = preload("res://Items/Consumables/Cooked_Pea_Soup/Cooked_Pea_Soup.tscn")
const Cooked_Meatballs = preload("res://Items/Consumables/Cooked_Meatballs/Cooked_Meatballs.tscn")
const Fruit_Kompot = preload("res://Items/Consumables/Fruit_Kompot/Fruit_Kompot.tscn")
const Tomato_Soup = preload("res://Items/Consumables/Tomato_Soup/Tomato_Soup.tscn")


const Battery = preload("res://Items/Electronics/Battery/Battery.tscn")
const Hotplate = preload("res://Items/Electronics/Hotplate/Hotplate.tscn")
const Battery_Cables = preload("res://Items/Electronics/Battery_Cables/Battery_Cables.tscn")
const Cooking_Station = preload("res://Items/Electronics/Cooking_Station/Cooking_Station.tscn")
const Inverter = preload("res://Items/Electronics/Inverter/Inverter.tscn")
const Polaris = preload("res://Items/Electronics/Polaris/Polaris.tscn")


const Happy_Stove = preload("res://Items/Utility/Happy_Stove/Happy_Stove.tscn")
const Mess_Kit = preload("res://Items/Utility/Mess_Kit/Mess_Kit.tscn")
const Sugar = preload("res://Items/Cooking/Sugar/Sugar.tscn")
const Yeast = preload("res://Items/Cooking/Yeast/Yeast.tscn")


const Toilet_Paper = preload("res://Items/Misc/Toilet_Paper/Toilet_Paper.tscn")
const Board_Game = preload("res://Items/Misc/Board_Game/Board_Game.tscn")
const Coffee = preload("res://Items/Misc/Coffee/Coffee.tscn")
const Cigar_Box = preload("res://Items/Misc/Cigar_Box/Cigar_Box.tscn")
const Duct_Tape = preload("res://Items/Misc/Duct_Tape/Duct_Tape.tscn")
const Matches = preload("res://Items/Misc/Matches/Matches.tscn")
const Gas_Canister = preload("res://Items/Misc/Gas_Canister/Gas_Canister.tscn")
const Tackle_Box = preload("res://Items/Misc/Tackle_Box/Tackle_Box.tscn")
const Fabric_Tarp = preload("res://Items/Fabrics/Fabric_Tarp/Fabric_Tarp.tscn")
const Fabric_Felt = preload("res://Items/Fabrics/Fabric_Felt/Fabric_Felt.tscn")
const Fabric_Leather = preload("res://Items/Fabrics/Fabric_Leather/Fabric_Leather.tscn")
const Bucket = preload("res://Items/Misc/Bucket/Bucket.tscn")
const Water_Lock = preload("res://Items/Misc/Water_Lock/Water_Lock.tscn")


const Book_Children = preload("res://Items/Books/Book_Children.tscn")
const Book_Cooking = preload("res://Items/Books/Book_Cooking.tscn")
const Book_Fishing = preload("res://Items/Books/Book_Fishing.tscn")
const Book_Religion = preload("res://Items/Books/Book_Religion.tscn")


const Guitar_Rig = preload("res://Items/Special/Guitar/Guitar_Rig.tscn")
const Guitar = preload("res://Items/Special/Guitar/Guitar_Pickup.tscn")
const Harmonica_Rig = preload("res://Items/Special/Harmonica/Harmonica_Rig.tscn")
const Harmonica = preload("res://Items/Special/Harmonica/Harmonica_Pickup.tscn")
const Accordion_Rig = preload("res://Items/Special/Accordion/Accordion_Rig.tscn")
const Accordion = preload("res://Items/Special/Accordion/Accordion_Pickup.tscn")


const Item_Common = preload("res://Debug/Item_Common.tscn")
const Item_Uncommon = preload("res://Debug/Item_Uncommon.tscn")
const Item_Rare = preload("res://Debug/Item_Rare.tscn")
const Item_Legendary = preload("res://Debug/Item_Legendary.tscn")
